config/routes.rb
TopTen::Application.routes.draw do
  get "ratings/create"


  get "videos/show"
  get 'videos/create'


  get "admin/index"
  get "admin/search"

  get "comedians/show"
  post "comedians/update"

  get "dashboard/shuffle"

  get "comments/random"

  match "comments/random", :as => "comments_random_path"

  match "comedians/update", :as => 'comedians_update_path'

  match "admin/search", :as => 'admin_search_path'

  devise_for :users

  resources :dashboard

  resources :videos do
    resources :comments
  end

  root to: "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessor :query
  attr_accessible :user_id


end

app/models/comedian.rb
class Comedian < ActiveRecord::Base
  attr_accessible :name, :bio, :photo
  has_many :videos, :dependent => :destroy, :inverse_of => :comedian

  validates :name, :format => { :with => /[A-Z][a-z\.0-9 ]*[A-Z][a-z\.0-9 ]*/, :message => "Is Not In Correct Format"}


  def rating
    @all_ratings = []
    self.videos.all.each do |video|
      @all_ratings << (video.ratings.average('thumbs')*100).to_i unless video.ratings.average('thumbs').nil?
    end
    sum = @all_ratings.inject(0) {|total, rating| total + rating}
    if @all_ratings.length == 0
      sum = 0
    else
      sum / (@all_ratings.length)
    end
  end

  def rank
    @all_comedians = []
    Comedian.all.each do |comedian|
      @all_comedians << comedian.rating
    end
    @all_comedians.sort.reverse.find_index(self.rating) + 1
  end

  def self.top_rated
    @ranked_hash, @ranked_array = {}, []
      Comedian.all.each do |comedian|
        @ranked_hash.merge!({comedian => comedian.rank}) unless Video.find(:all, :conditions => {:comedian_id => comedian.id}).empty?
      end
      @ranked_hash.sort_by {|key, value| value}.each{ |key, value| @ranked_array << key }
      @ranked_array
  end

  def self.recently_added
    Comedian.find(:all, :order => 'created_at DESC')
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :description, :video_id, :user_id
  belongs_to :video
  belongs_to :user, :inverse_of => :comments
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :thumbs, :video_id, :user_id
  belongs_to :video, :counter_cache => true

  validates_uniqueness_of :video_id, :scope => :user_id, :message => "You've already rated this video"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  has_many :comments, :inverse_of => :user
  # attr_accessible :title, :body
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :title, :comedian_id, :url, :ratings_count
  has_one :comedian
  belongs_to :comedian, :inverse_of => :videos
  has_many :ratings
  has_many :comments

  def random_comment
    @random_comments = []
    if self.comments.first != nil
      self.comments.all.each do |comment|
        @random_comments << comment if !comment.nil?
      end
      @random_comments.shuffle.first.description
    else
     false
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!

  def index
    unless !@admin.nil?
        redirect_to dashboard_index_path(current_user.id)
        flash[:alert] = "You do not have access to this page"
    end
    @comedians = Comedian.all
  end

  def search
    @results = []
    if !Comedian.find_by_name(params[:query]).nil?
      @comedian = Comedian.find_by_name(params[:query])
    else
      @comedian = Comedian.new(:name => params[:query])
    end
    if @comedian.save
      10.times do |i|
        @results << yt_client.videos_by(:page => i, :query => params[:query], :per_page => 50,
                                      :duration => "short", :tags => ["stand-up"], :categories => [:comedy],
                                      :fields => { :published => (Date.new(2010)..Date.today) }).videos
      end
    end
    respond_to do |format|
      format.js {render 'search.js.coffee.erb'}
    end
  end


  def show
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :yt_client
  before_filter :set_admin


  private
    def set_admin
      @admin = Admin.find_by_user_id(current_user.id) if current_user !=nil
    end

    def yt_client
      @yt_client ||= YouTubeIt::Client.new(:dev_key => "AI39si7F87ZBi_Vp0PPnGiDdjGoKrEPmsVCzbQ7NQn1-1Zm9gCiKwhZIXEmaVK6ficykFRSKKBh4ekkzIwr19Ahrq72MWurw_w")
    end
end

app/controllers/comedians_controller.rb
class ComediansController < ApplicationController
  def show
    @comedian = Comedian.find(params[:id])
    @videos = @comedian.videos.all
    if params[:video_id].nil?
      @start_video = @comedian.videos.first
    else
      @start_video = @comedian.videos.find(params[:video_id])
    end
  end

  def update
    @comedian = Comedian.find(params[:id])
    if @comedian.update_attributes(params[:comedian])
      respond_to do |format|
        format.js { render 'update.js.coffee.erb' }
      end
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @video = Video.find(params[:video_id])
    @comment = @video.comments.new(params[:comment])
    @comment.user_id = current_user.id
    if @comment.save
      respond_to do |format|
        format.js {render 'create.js.coffee.erb'}
      end
    end
  end

  def random
    @video = Video.find(params[:video_id])
    respond_to do |format|
      format.js {render 'random.js.coffee.erb'}
    end
  end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
      @top_comedians = Comedian.top_rated
      @recent_comedians = Comedian.recently_added
      @random_video = Video.first(:offset => rand(Video.count))   
  end

  def shuffle
    @random_video = Video.first(:offset => rand(Video.count))
    respond_to do |format|
      format.js{render 'shuffle.js.coffee.erb'}
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      if !@admin.nil?
        redirect_to :controller => 'admin', :action => 'index'
      else
        redirect_to :controller => 'dashboard', :action => 'index'
      end
    else
      redirect_to :controller => 'dashboard', :action => 'index'
    end
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @video = Video.find(params[:video_id])
    @rating = @video.ratings.new(:thumbs => params[:thumbs], :user_id => current_user.id)
    if @rating.save
      respond_to do |format|
        format.js{render 'create.js.coffee.erb'}
      end
    else
      respond_to do |format|
        format.js {render 'errors.js.coffee.erb'}
      end
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!

  def create
    @video = Video.new(:comedian_id => params[:comedian_id], :title => params[:title], :url => params[:url])
    @counter = params[:counter]
    if @video.save
      respond_to do |format|
        format.js {render 'create.js.coffee.erb'}
      end
    end
  end


  def show
    @comedian = Comedian.find(params[:comedian_id])
    @video = @comedian.videos.find(params[:id])
    respond_to do |format|
      format.js {render 'show.js.coffee.erb'}
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comedians_helper.rb
module ComediansHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comedians/show.html.erb
<div id="show_top">

  <div id = "left">
    <div id = "comedian_name_header">
      <%= @comedian.name %>
    </div>
    <div id="comedian_info_div">
      <div id="photo_div">
        <%= image_tag @comedian.photo, :id => "photo" %>
      </div>
      <div id="bio">
        <%= @comedian.bio%>
      </div>
      <div id="stats">
        <div id="stats_title"> Statistics: </div>
        <div class="stats_row">Average Video Rating: <%= @comedian.rating %>%</div>
        <div class="stats_row">Number of Videos: <%= @comedian.videos.all.length %></div>
        <div class="stats_row">
          Current Rank: <% if @comedian.rank.to_s[-1] != '1' %>
                            <%= @comedian.rank.to_s + "th"%>
                        <% else %>
                          <%= @comedian.rank.to_s + "st" %>
                        <% end %>
        </div>
      </div>
    </div>
  </div>

  <div id="right">
    <div id="current_video_div">
      <%= render :partial => 'videos/show', :locals => {:video => @start_video, :videos => @videos, :comedian => @comedian} %>
   </div>

</div>

app/views/comedians/update.js.coffee.erb
$('#edit_comedian')
    .html('Comedian Attributes Updated.')
        .css('background', 'lightgreen')
            .css('border', 'none')
                .fadeOut('slow')
$('#loading_div').fadeOut('fast')
$('#comedian_info').hide()

app/views/comments/_random_comment.html.erb
<%= video.random_comment unless Comment.find(:all, :conditions => {:video_id => video.id }).empty? %>

app/views/comments/create.js.coffee.erb
$('#check_mark').show()
$('#add_comment_button').hide()

app/views/comments/random.js.coffee.erb
$("#random_comment_text").html("<%= j(render :partial => 'comments/random_comment', :locals => {:video => @video}) %>")

app/views/dashboard/_random_video.html.erb
<div id="dash_above_video">
  <div id="dash_now_playing_text">
    <%=link_to video.comedian.name + ":", comedians_show_path(:id => video.comedian), :id=>'dash_random_comedian_link'%> <span id = "dash_video_title" ><%= video.title%></span>
  </div>
</div>

<div id="dash_video_player"></div>
<script type='text/javascript'>
    jwplayer('dash_video_player').setup({
        file: "<%= video.url %>",
        width: '700',
        height: '393',
        controlbar: 'none',
        autostart: 'true',
        icons: 'false',
        logo: 'false',
        fill: 'true',
        smoothing: 'true'

    });
</script>
<div id="dash_below_video">
  <div id="rating_div">
    <%= button_to  '', ratings_create_path(:video_id => video.id, :thumbs => 1), :method => 'get', :remote => true, :id => "thumbs_up_button"%>
    <%= button_to  '', ratings_create_path(:video_id => video.id, :thumbs => 0), :method => 'get', :remote => true, :id => "thumbs_down_button"%>

    <div id = "approval_rating">
      Approval Rating: <%= (video.ratings.average('thumbs')*100).to_i unless video.ratings.average('thumbs').nil? %>%
    </div>
  </div>

  <div id="dash_next_video_div">
      <%= button_to "Shuffle",  dashboard_shuffle_path, :remote => true, :method => :get, :id => "dash_next_video_button" %>
      <div id = "dash_more_from_div">
        <div id= "dash_more_from_header">
          More from <%= video.comedian.name%>:
        </div>
          <div id="dash_more_from_videos">
            <% video.comedian.videos.all.each_with_index do |video, i|%>
              <% if i < 3 %>
                <div class= "dash_more_from_row">
                  <%=link_to video.title, comedians_show_path(:id => video.comedian.id, :video_id => video.id) %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>


  </div>
</div>

<div id="dash_comments">
  <div class="comments_header_div"><%=video.comments.all.length%> Comments:</div>
  <div class="dash_comments_div">
  <% unless Comment.find(:all, :conditions => {:video_id => video.id }).empty? %>
    <% video.comments.all.each do |comment| %>
      <div id="dash_comment_item">
        <div id="dash_comment_name"><%= comment.user.name %> said: </div>
        <div id="dash_comment_description"><%= comment.description %></div>
        <div id= "dash_comment_date">Posted <%= comment.created_at.strftime("%b %d, %Y")%></div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div id="dash_left">
  <div id= "dash_top_comics_div" class = "dash_rank_div">
    <div class ="dash_comics_header">
      Top-Rated:
    </div>
      <div id = "dash_top_comics" class="dash_rank_items">
	<% if !@top_comedians.nil? %>
        <% @top_comedians.each_with_index do |comedian, i| %>
             <%if i < 10 %>

          <div class="dash_comedian_link">
            <%=link_to image_tag(comedian.photo, :class => "dash_comic_image"), comedians_show_path(:id => comedian), :class =>"dash_comic_link" %>
          </div>

          <% end %>
        <% end %>
<%end%>
      </div>
  </div>

  <div id= "dash_recent_comics_div" class="dash_rank_div">
    <div class ="dash_comics_header" id = "dash_recent_comics_header">
      Recently-Added:
    </div>
      <div id = "dash_recent_comics" class="dash_rank_items">
	<% if !@recent_comedians.nil? %>
        <% @recent_comedians.each_with_index do |comedian, i| %>
             <%if i < 10 %>

          <div class="dash_comedian_link">
            <%=link_to image_tag(comedian.photo, :class => "dash_comic_image"), comedians_show_path(:id => comedian), :class =>"dash_comic_link" %>
          </div>

          <% end %>
        <% end %>
	<%end%>
      </div>
  </div>
</div>

<div id="dash_right">
  <div id="dash_random_video_div">
    <%= render :partial => "random_video", :locals=>{:video => @random_video} unless @random_video.nil?%> 
  </div>
</div>

app/views/dashboard/shuffle.js.coffee.erb
$('#dash_random_video_div').html("<%= j(render :partial => 'random_video', :locals=>{:video => @random_video})%>")

$('#dash_video_player_wrapper').css('right', '-1000px')
$('#dash_above_video').css('right', '-1000px')
$('#dash_video_player_wrapper').animate({
    right: '+=900',
  }, 600, function() {
});

$('#dash_above_video').animate({
    opacity: 1,
    right: '+=900',
  }, 600, function() {
});

app/views/ratings/create.js.coffee.erb
$('#rating_div').html("rating saved")

app/views/ratings/errors.js.coffee.erb
$('#rating_div').html('you already rated this video').css('color', 'red')

app/views/videos/_show.html.erb
<div class="horizontal_scroller" >
  <div id= "video_description_title" class="scrolling_text">Now Playing: <%= video.title %></div>
</div>
<div id="video_player"></div>
<script type='text/javascript'>
    jwplayer('video_player').setup({
        file: "<%= video.url %>",
        width: '660',
        height: '364',
        controlbar: 'none',
        autostart: 'true',
        icons: 'false',
        logo: 'false',
        fill: 'true',
        smoothing: 'true'

    });
</script>

<div id="below_video">
  <div id="rating_div">
    <%= button_to  '', ratings_create_path(:video_id => video.id, :thumbs => 1), :method => 'get', :remote => true, :id => "thumbs_up_button"%>
    <%= button_to  '', ratings_create_path(:video_id => video.id, :thumbs => 0), :method => 'get', :remote => true, :id => "thumbs_down_button"%>

    <div id = "approval_rating">
      Approval Rating: <%= (video.ratings.average('thumbs')*100).to_i unless video.ratings.average('thumbs').nil? %>%
    </div>
  </div>

    <div id="video_list">
      <% comedian.videos.all.each do |vid| %>
        <div class="comedian_video_item">
          <div class="video_title">
            <%= vid.title %>
          </div>
          <div class="play_video_button_div">
            <%= button_to '', videos_show_path(:comedian_id => comedian.id, :id => vid.id), :remote => true, :method => 'get', :class => "play_video_button" %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
  <div id="comments">
    <div id="new_comment">
      <%= form_for video.comments.new, :url => video_comments_path(:video_id => video.id), :remote => true, :method => 'post' do |f| %>
        <div id="comment_title">Leave a Comment: </div>
        <%= f.text_area :description, :size => "35x5", :id => "comment_box"%>
        <div id="add_and_submit_comment">
        <%= f.submit "add comment", :id => "add_comment_button"%>
        </div>
        <%= image_tag 'check_mark.png', :id => 'check_mark' %>
      <% end %>
    </div>
  </div>

  <div id="random_comment_box">

    <div id="random_comment_text">
        <%= video.random_comment unless Comment.find(:all, :conditions => {:video_id => video.id }).empty? %>
    </div>
  </div>
</div>



<%= button_to "", comments_random_path(:video_id => video.id), :remote => true, :id => "hidden_refresh_comment_button" %>

app/views/videos/create.js.coffee.erb
$('#<%= @counter %>').closest('td').css('background', 'lightgreen').html("<div style='color:white; font-weight:bold; text-align: center;'>  Added </div>")
$('#loading_div').fadeOut('fast')

app/views/videos/destroy.html.erb
<h1>Videos#destroy</h1>
<p>Find me in app/views/videos/destroy.html.erb</p>

app/views/videos/edit.html.erb
<h1>Videos#edit</h1>
<p>Find me in app/views/videos/edit.html.erb</p>

app/views/videos/index.html.erb
<h1>Videos#index</h1>
<p>Find me in app/views/videos/index.html.erb</p>

app/views/videos/new.html.erb
<h1>Videos#new</h1>
<p>Find me in app/views/videos/new.html.erb</p>

app/views/videos/show.js.coffee.erb
$("#current_video_div").html("<%= j(render :partial => 'videos/show', :locals => {:video => @video, :comedian => @comedian}) %>")

app/views/videos/update.html.erb
<h1>Videos#update</h1>
<p>Find me in app/views/videos/update.html.erb</p>