config/routes.rb
TopTen::Application.routes.draw do
  get "ratings/create"


  get "videos/show"
  get 'videos/create'


  get "admin/index"
  get "admin/search"

  get "comedians/show"
  post "comedians/update"

  get "dashboard/shuffle"

  get "comments/random"

  match "comments/random", :as => "comments_random_path"

  match "comedians/update", :as => 'comedians_update_path'

  match "admin/search", :as => 'admin_search_path'

  devise_for :users

  resources :dashboard

  resources :videos do
    resources :comments
  end

  root to: "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessor :query
  attr_accessible :user_id


end

app/models/comedian.rb
class Comedian < ActiveRecord::Base
  attr_accessible :name, :bio, :photo
  has_many :videos, :dependent => :destroy, :inverse_of => :comedian

  validates :name, :format => { :with => /[A-Z][a-z\.0-9 ]*[A-Z][a-z\.0-9 ]*/, :message => "Is Not In Correct Format"}


  def rating
    @all_ratings = []
    self.videos.all.each do |video|
      @all_ratings << (video.ratings.average('thumbs')*100).to_i unless video.ratings.average('thumbs').nil?
    end
    sum = @all_ratings.inject(0) {|total, rating| total + rating}
    if @all_ratings.length == 0
      sum = 0
    else
      sum / (@all_ratings.length)
    end
  end

  def rank
    @all_comedians = []
    Comedian.all.each do |comedian|
      @all_comedians << comedian.rating
    end
    @all_comedians.sort.reverse.find_index(self.rating) + 1
  end

  def self.top_rated
    @ranked_hash, @ranked_array = {}, []
      Comedian.all.each do |comedian|
        @ranked_hash.merge!({comedian => comedian.rank}) unless Video.find(:all, :conditions => {:comedian_id => comedian.id}).empty?
      end
      @ranked_hash.sort_by {|key, value| value}.each{ |key, value| @ranked_array << key }
      @ranked_array
  end

  def self.recently_added
    Comedian.find(:all, :order => 'created_at DESC')
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :description, :video_id, :user_id
  belongs_to :video
  belongs_to :user, :inverse_of => :comments
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :thumbs, :video_id, :user_id
  belongs_to :video, :counter_cache => true

  validates_uniqueness_of :video_id, :scope => :user_id, :message => "You've already rated this video"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  has_many :comments, :inverse_of => :user
  # attr_accessible :title, :body
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :title, :comedian_id, :url, :ratings_count
  has_one :comedian
  belongs_to :comedian, :inverse_of => :videos
  has_many :ratings
  has_many :comments

  def random_comment
    @random_comments = []
    if self.comments.first != nil
      self.comments.all.each do |comment|
        @random_comments << comment if !comment.nil?
      end
      @random_comments.shuffle.first.description
    else
     false
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!

  def index
    unless !@admin.nil?
        redirect_to dashboard_index_path(current_user.id)
        flash[:alert] = "You do not have access to this page"
    end
    @comedians = Comedian.all
  end

  def search
    @results = []
    if !Comedian.find_by_name(params[:query]).nil?
      @comedian = Comedian.find_by_name(params[:query])
    else
      @comedian = Comedian.new(:name => params[:query])
    end
    if @comedian.save
      10.times do |i|
        @results << yt_client.videos_by(:page => i, :query => params[:query], :per_page => 50,
                                      :duration => "short", :tags => ["stand-up"], :categories => [:comedy],
                                      :fields => { :published => (Date.new(2010)..Date.today) }).videos
      end
    end
    respond_to do |format|
      format.js {render 'search.js.coffee.erb'}
    end
  end


  def show
  end



end

app/controllers/comedians_controller.rb
class ComediansController < ApplicationController
  def show
    @comedian = Comedian.find(params[:id])
    @videos = @comedian.videos.all
    if params[:video_id].nil?
      @start_video = @comedian.videos.first
    else
      @start_video = @comedian.videos.find(params[:video_id])
    end
  end

  def update
    @comedian = Comedian.find(params[:id])
    if @comedian.update_attributes(params[:comedian])
      respond_to do |format|
        format.js { render 'update.js.coffee.erb' }
      end
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @video = Video.find(params[:video_id])
    @comment = @video.comments.new(params[:comment])
    @comment.user_id = current_user.id
    if @comment.save
      respond_to do |format|
        format.js {render 'create.js.coffee.erb'}
      end
    end
  end

  def random
    @video = Video.find(params[:video_id])
    respond_to do |format|
      format.js {render 'random.js.coffee.erb'}
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      if !@admin.nil?
        redirect_to :controller => 'admin', :action => 'index'
      else
        redirect_to :controller => 'dashboard', :action => 'index'
      end
    else
      redirect_to :controller => 'dashboard', :action => 'index'
    end
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @video = Video.find(params[:video_id])
    @rating = @video.ratings.new(:thumbs => params[:thumbs], :user_id => current_user.id)
    if @rating.save
      respond_to do |format|
        format.js{render 'create.js.coffee.erb'}
      end
    else
      respond_to do |format|
        format.js {render 'errors.js.coffee.erb'}
      end
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!

  def create
    @video = Video.new(:comedian_id => params[:comedian_id], :title => params[:title], :url => params[:url])
    @counter = params[:counter]
    if @video.save
      respond_to do |format|
        format.js {render 'create.js.coffee.erb'}
      end
    end
  end


  def show
    @comedian = Comedian.find(params[:comedian_id])
    @video = @comedian.videos.find(params[:id])
    respond_to do |format|
      format.js {render 'show.js.coffee.erb'}
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comedians_helper.rb
module ComediansHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/_search_results.html.erb
<div id="comedian_info">Comedian Info:</div>
<div id = "edit_comedian">
  <%= form_for comedian, :url => comedians_update_path(:id => comedian.id), :remote => true, :id => "edit_comedian_form" do |f| %>
    <p><%= f.label :name %>
    <%= f.text_field :name %></p>
    <p><%= f.label :photo_url %>
    <%= f.text_field :photo %></p>
    <p><%= f.label :bio %>
    <%= f.text_area :bio, :size =>'70x5'%></p>
    <%= f.submit "update" %>
  <% end %>
</div>


<div id = "results">
  <p>Results:</p>
  <% comedian.errors.full_messages.each do |error| %>
    <%= javascript_tag "$('#results_table').hide()" %>
    <p class = "error"> Errors:  <%= error  %></p>
  <% end %>
  <table id = "results_table">
    <tr id = "row_header">
      <td><b>number</b></td>
      <td><b>add video</b></td>
      <td><b>title</b></td>
      <td><b>preview</b></td>
      <td><b>duration</b></td>
      <td><b>view count</b></td>
    </tr>
    <% $counter = 0%>
    <% results.each do |page|%>
      <% page.each do |result|%>
        <% if (result.duration) < 300 && !result.noembed && comedian.videos.find_by_url(result.embed_html5).nil? && comedian.videos.find_by_title(result.title.gsub!(/#{comedian.name}|-|:|on/, '' )).nil? %>
          <% $counter += 1%>
    <td class="row_number"><%= $counter %></td>
    <td><%= button_to "add_video",  videos_create_path(:title => result.title,  :url => result.player_url, :comedian_id => comedian.id, :counter => $counter), :method => 'get', :remote => true, :id => $counter, :class => "add_button" %></td>
    <td><%= result.title %></td>
    <td class = 'video_preview' style="width: 200px; height: 100px; padding: 4px; background: url(<%= result.thumbnails[1].url %>); background-size: 94% 90%; background-repeat: no-repeat; background-position: center;"><%= button_tag "play", :class => "play_preview_button", :value => result.embed_html5({:width => '195', :height => '100', :url_params => {:controls => "0", :showinfo => "0", :autoplay => "1"}}) %></td>

    <td><%= (result.duration) %> </td>
    <td><%= result.view_count %></td>
    </tr>
  <% end %>
  <% end %>
  <%end%>
  </table>
</div>

app/views/admin/index.html.erb
<h1>Admin Panel </h2>
<div id = "top">
  <div id = "search_form">
    <%= form_tag admin_search_path, :controller => 'admin', :remote => true, :method => 'get' do |f| %>
      <%= label_tag :keywords %>
      <%= text_field_tag :query %>
      <%= submit_tag "search", :id => "search"%>
    <% end %>
  </div>
</div>


<div id = "middle">
  <div id = "loading_div" style="display:none;">
   <%= image_tag 'ajax_spinner.gif', :width=> '50', :height => '50', :id => 'ajax_spinner'%>
  </div>
</div>

<div id="search_results">
</div>

app/views/admin/search.js.coffee.erb
$("#search_results").html("<%= j(render :partial => 'admin/search_results', :locals => {:results => @results, :comedian => @comedian}) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comic Shuffle</title>
<link href='http://fonts.googleapis.com/css?family=Fugaz+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="/jwplayer/jwplayer.js"></script>
  <script>jwplayer.key="4i54KFXD0bf9hpGXzeqFteZuR5MyJkN09/1xxA=="</script>
  <link href='http://fonts.googleapis.com/css?family=Ranchers' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="background">
    <div id = "container">
      <div id="logo">
        <h1> Comic Shuffle </h1>
      </div>
      <div id = "header">

        <div id="user_nav">
          <% if user_signed_in? %>
            Signed in as <%= current_user.email %>.  Not you?
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete%>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
          <% end %>
        </div>
        <div id = "nav_links_div">
          <%= link_to "HOME", dashboard_index_path, :id => "home_link", :class => "nav_link" %>
          <%= link_to("ADMIN", admin_index_path, :id => "admin_link", :class => "nav_link") unless @admin.nil? %>

        </div>
      </div>
        <span id = "flash_notices">
          <span class="notice" style = 'color: green; font-weight: bold; font-size: 18pt'><%= notice %></span>
          <span class="alert" style = 'color: red; font-weight: bold; font-size: 18pt'><%= alert %></span>
        </span>
      <div id = "content">
        <%= yield %>
      </div>
    </div>
  </div>
</body>

</html>